// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyXwCebfR_IZo88D5YAP5So8kz3_UURqk',
    appId: '1:670931725347:web:3050b691799d4f6b7b5596',
    messagingSenderId: '670931725347',
    projectId: 'tic-tac-toe-ad309',
    authDomain: 'tic-tac-toe-ad309.firebaseapp.com',
    storageBucket: 'tic-tac-toe-ad309.appspot.com',
    measurementId: 'G-6T8Y11ZBKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcrlCrM-PsFxOJF_G4XjD7Qxsc3xl_I4Q',
    appId: '1:670931725347:android:3073aed4d56207777b5596',
    messagingSenderId: '670931725347',
    projectId: 'tic-tac-toe-ad309',
    storageBucket: 'tic-tac-toe-ad309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS3HGhC4YsFKLoa1KGBjw05jM_CcL3sV0',
    appId: '1:670931725347:ios:d723f6407cca18207b5596',
    messagingSenderId: '670931725347',
    projectId: 'tic-tac-toe-ad309',
    storageBucket: 'tic-tac-toe-ad309.appspot.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyXwCebfR_IZo88D5YAP5So8kz3_UURqk',
    appId: '1:670931725347:web:2efddb87929f1e867b5596',
    messagingSenderId: '670931725347',
    projectId: 'tic-tac-toe-ad309',
    authDomain: 'tic-tac-toe-ad309.firebaseapp.com',
    storageBucket: 'tic-tac-toe-ad309.appspot.com',
    measurementId: 'G-7HJX082J17',
  );
}
